spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.245.151:3306/bookshop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5 #连接池初始化时初始化的数据库连接数
    minIdle: 10 #连接池中的最小空闲连接数
    maxActive: 12 #最大连接池数量
    maxWait: 60000 #最大建立连接等待时间，如果超过此时间将接到异常，设为-1表示无限制。
    timeBetweenEvictionRunsMillis: 60000 #Destroy线程会检测连接的间隔时间，testWhileIdle的判断依据
    minEvictableIdleTimeMillis: 500000 #连接保持空闲而不被驱逐的最小时间
    validationQuery: SELECT 1 FROM DUAL #用来检测连接是否有效的sql
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。
                        #申请连接的时候检测，如果空闲时间大于
                        #timeBetweenEvictionRunsMillis，
                        #执行validationQuery检测连接是否有效。
    testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j #属性类型是字符串，通过别名的方式配置扩展插件，
                              #常用的插件有：
                              #监控统计用的filter:stat
                              #日志用的filter:log4j
                              #防御sql注入的filter:wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

  redis:
    host: 47.106.245.151 #虚拟机：192.168.73.132
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zjh/bookshop/mapper/xml/*.xml
  type-aliases-package: com.zjh.bookshop.*.entity

server:
  port: 18080
  servlet:
    context-path: /

#JWT 配置
audience:
  header: Authorization
  # 有空格
  tokenHead: Bearer #可删，得看前端怎么验证
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M1NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 18000 #token 过期时间（半个小时，单位s）
  refreshExpiresSecond: 86400 #refeshtoken过期时间一天（单位s）
  whiteList:
    ## - /**/
    - /**/categories/**
    - /**/video/**
    - /**/register
    - /**/qiniu/**
    - /**/wx/notify/**
    - /**/token/**
    - /**/tmp/**
    - /**/images/**
    - /**/api/**
    - /**/chat/**

alipay:
  # 支付宝网关
  url: https://openapi.alipaydev.com/gateway.do
  # APPID 即创建应用后生成
  app_id: 2021000116698867
  # 开发者私钥，由开发者自己生成
  app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCTVmOmWzclkxkJrwYWLtw6e0vE7R91FCAmzzboTe1zoLUz6d8gRVIVlxTsSEe2fcDukiIIRpAeg4aipBysRnO2Agyo0L64nrxBW6r5SZB5Py6BpFgDHmScgvkK2Svwt8+Ca3Wa3zKRA2QnpsnbLxliGz3NzOeOsLZe17tHhWsqUZ+wKyMbvS/1w9Z45VkOU6SF0EJHuaJUayZQAFR8s9gltjELuSkOrjyces3QiWGp1HFly8pIET3u1LYzOJfCPAn8o/E0vPT5KgrTamq9hzQQaq0+CNg4Uc1EYZCVDvbSkbJH7TNew5OlgPZOK2LEpnXry7hlsJnuCsDYlnRp3trNAgMBAAECggEAMAeVbIGHtKQDIXkAzvJvsFDJHmT+QDhTUtNx3sCoi2z0JPw0VFzEqW0a0PuvBPpxjlPs7C20hX3ywcol3rMIvWhloBKMWbrFO7kaPzGP+zZxfqmIV1vtCGhZrwOko1AIQUeuitH/te4ZFCP24ZC1AZpHx3LoeUd56+j/kA0aJiz9QhYN80ruYhR/m+c3SNX66VmfMQd5qLE2qa37mB8zIkQ9XXouJOPBxvbn8AVk//fIChyKY0mVyr0YIzRG8g1OLv0sstl2M7PyTwzr5rj6nioKkz0G85TEETnrp8MZsKI3WXb1/TQzzMIUpEiOtlm+7TVSjUc5MGTB6641HBtIMQKBgQDkytBJKpkBW7rxzC3mQ5BMQ5gVBfBkqqLjDFBcdGKQLBlsKkc9eXx8/88FWNnLfmKPi0m3EUoc1Lryvmb/Iq1ceauX8zC9rt2+hSP1Sc9d0acMGnI9i1RXAnlulmIEEdpYTb1xRN16UHqBPoRVJ/4bXcmRoXDr0PqYK0KiV5Q+GwKBgQCk29Mob9xQMHS3zm0d9BCEULx1yvsa3Px3qpZ0SuiDP40l32OwcmvnplhM3bcZfA47v+Y+vMskgE2XKhbUs3Ibp1uFl47jNIL2nfIpGh/U0UgaJlM8GbOCKx2dA4gSY/h9czuajlhay2R7N0b2njvezyTO+T1BBuVH3/0zGqy5NwKBgQCczM6wxkv0XVyi6I8wd2+GhPDOv7JAG53kw4SzyGPgcQi/U75dSExkEqFcBcfGKgj8XbaYi3XiinzRbmKCSs7LSOusCNSHuzdnojHBouNGZi/5IIrY2QtlUmHMw63LIj0lNao23b54XH2I5EKnZfBF6yIA98a/JwsHjOZvAlyrrwKBgEEHQPyTWyj6ZB/Yuiv1iMpYem5QWcpX3vJpBJ3sqliTKd8FhfIkwDGI6Q2w6zePOqIQ6QZYPB0yyuhUvtq5ycnksvI4PTGcFginds0FtAajYriF45EyZh9zWGQF75epfWwmlx05BtsRnZoIzOIcumsB9Hf70lCjIq++R8bvv6/zAoGBALuD+eGAC3J4DEJR9Q46COAgyNi7MOZHIGP/iO+rIgvkB4o2PjnOBL+hgcuxTY60X+0UTUzA8rvzlw1t18p51KA0o7+x+nPJkuV06BtDJ+nJeDZ0VNs3xcfd+ghtDVjR9xuWeKrHggUrnwyitUHaCY1TByuQIhljzeLiJT9KSVsR
  # 支付宝公钥，由支付宝生成
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlLdimjoGesUtuo9Z55lA6ucOpmlXTowB4duO/4cfYE7nP5nrPKOc7T/wwRfTE48KEJDwVVhFZkI8aMxnO0YJjd9vpwdbhWvj8dSxaVSUOIQzDHPK/ckHk23mKKm3utFKgkXjXW+zRc5QS47XJakvcm9jAnfYE7otndMTVHZcJJI5FbeLEb1mAZhgcYikRIuGgNxdP+Exb7IFTBHgsk+6k6S4szCPVS3RPtNW8xit6BU/337xcWIeezIkLI6Rol84fmz4ZSlZaJHKtXiMH00brObNcdQ/U01wS+jNzCGsXiGXP2uB3T3/xfZ4UlcYeYOZJdAb3k9XpiA8BZsi/TvFXQIDAQAB
  format: json
  charset: UTF-8
  sign_type: RSA2
  notify_url: http://47.106.245.151:18080/bookshop/pay/notify_url
  return_url: http://47.106.245.151:18080/bookshop/pay/return_url